version: '3.8'  # Actualiza a una versión más reciente

services:
  spring-app:
    build:
      context: .
      dockerfile: images/Dockerfile  # Asegúrate de que la ruta sea correcta
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev  # Ejemplo de variable de entorno (ajusta según tu necesidad)
    depends_on:
      # Puedes agregar otros servicios aquí si es necesario, como bases de datos.
